service: javascript-template

frameworkVersion: '3'

provider:
  deploymentBucket:
    name: com.reference-architecture.deploys
  logRetentionInDays: 7
  name: aws
  runtime: nodejs20.x

custom:
  esbuild:
    bundle: true # DEFAULT
    format: esm
    minify: false
    platform: node # DEFAULT

functions:
  hello:
    handler: src/helloWorld.helloHandler
    events:
      - httpApi:
          method: get
          path: /hello

plugins:
  - serverless-deployment-bucket
  - serverless-esbuild

package:
  individually: true
