service: javascript-template

licenseKey: ${ssm:/aws/reference/secretsmanager/serverless-framework-access-key}

provider:
  deploymentBucket:
    name: com.reference-architecture.deploys
  logRetentionInDays: 7
  name: aws
  runtime: nodejs20.x

functions:
  hello:
    handler: src/helloWorld.helloHandler
    events:
      - httpApi:
          method: get
          path: /hello

build:
  esbuild:
    bundle: true
    minify: true
    exclude:
      - '@aws-sdk/*'

plugins:
  - serverless-deployment-bucket

package:
  individually: true
